CREATE TABLE databases (
  db_id int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  db_name VARCHAR(128) NOT NULL CONSTRAINT DB_NAME_UNIQ UNIQUE,
  CONSTRAINT DATABASES_PK PRIMARY KEY (db_id)
)