CREATE TABLE databases (
  DB_ID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  DB_NAME VARCHAR(128) NOT NULL CONSTRAINT DB_NAME_UNIQ UNIQUE,
  URL VARCHAR (1024) NOT NULL,
  CONSTRAINT DATABASES_PK PRIMARY KEY (DB_ID)
)