CREATE TABLE INDEXES (
  DB_ID INT NOT NULL REFERENCES DATABASES (DB_ID) ON DELETE CASCADE,
  TID INT NOT NULL REFERENCES TABLES (TID) ON DELETE CASCADE,
  index_name VARCHAR(128) NOT NULL,
  column_name VARCHAR(128) NOT NULL,
  data_type VARCHAR(128) NOT NULL,
  index_type CHAR(32) NOT NULL,
  is_unique BOOLEAN NOT NULL,
  is_clustered BOOLEAN NOT NULL,
  is_ascending BOOLEAN NOT NULL,
  CONSTRAINT C_INDEXES_PK PRIMARY KEY (DB_ID, index_name)
)