CREATE TABLE TABLES (
  TID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  DB_ID int NOT NULL REFERENCES DATABASES (db_id),
  TABLE_ID VARCHAR(128) NOT NULL,
  TABLE_TYPE VARCHAR(128) NOT NULL,
  path VARCHAR(1024),
  store_type CHAR(16),
  CONSTRAINT TABLES_PK PRIMARY KEY (TID)
)