CREATE TABLE tables (
  db_id int NOT NULL REFERENCES DATABASES (db_id),
  TID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  TABLE_ID VARCHAR(255) NOT NULL CONSTRAINT TABLE_ID_UNIQ UNIQUE,
  path VARCHAR(1024),
  store_type CHAR(16),
  CONSTRAINT TABLES_PK PRIMARY KEY (TID)
)